config/routes.rb
Rails.application.routes.draw do
  root 'ads#index'
  get 'new_ad' => 'ads#new'
  resources :ads
end

app/models/ad.rb
class Ad < ActiveRecord::Base
    has_many :creatives, dependent: :destroy, inverse_of: :ad
    has_many :targetings, dependent: :destroy, inverse_of: :ad
    
    default_scope -> { order(updated_at: :desc) }
    
    accepts_nested_attributes_for :creatives, allow_destroy: true, reject_if: :all_blank
    accepts_nested_attributes_for :targetings, allow_destroy: true, reject_if: :all_blank
    
    validates :creatives, presence: true
    validates :targetings, presence: true
    
    validates :budget, presence: true, numericality: { greater_than: 0}
end

app/models/creative.rb
class Creative < ActiveRecord::Base
  belongs_to :ad, inverse_of: :creatives, touch: true
  
  validates :ad_text, presence: true
  validates :bid,     presence: true, numericality: { less_than_or_equal_to: :ad_budget }
  
  private
    def ad_budget
      ad.budget || 0
    end
end

app/models/targeting.rb
class Targeting < ActiveRecord::Base
  belongs_to :ad, inverse_of: :targetings, touch: true
  serialize :places,Array
  as_enum :gender, male: 0, female: 1, undetermined: 2

  before_validation do |targeting|
    targeting.places.reject!(&:blank?) if targeting.places
  end
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  def new
    @ad = Ad.new
  end
  
  def edit
    @ad = Ad.find(params[:id])
    render 'new'
  end
  
  def create
    @ad = Ad.new(ad_params)
    if @ad.save
      flash[:success] = "Ad created successfully!"
      redirect_to root_url
    else
      render 'new'
    end
  end
  
  def update
    @ad = Ad.find(params[:id])
    if @ad.update_attributes(ad_params)
      flash[:success] = "Ad updated successfully!"
      redirect_to root_url
    else
      render 'new'
    end
  end
  
  def index
    @ads = Ad.paginate(page: params[:page], per_page: 10)
  end
  
  def ad_params
    params.require(:ad).permit(:budget, creatives_attributes: [:id, :bid, :ad_text, :_destroy], 
                                        targetings_attributes: [:id, :gender, :_destroy, places: []])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ads/index.html.erb
<% provide(:title, "List of Ads") %>
<div class="row">
    <div class="col-md-5">
        <div class="row">
            <div class="col-md-8">
                <h2>List of Ads</h2>
            </div>
            <div class="col-md-4">
                <%= link_to new_ad_path, class: "new-ad-icon pull-right" do %>
                  <i class="fa fa-plus-square-o fa-lg"></i>
                <% end %>
            </div>
        </div>
    </div>
    <div class="col-md-7"></div>
</div>
<div class="list-group">
    <div class="row">
        <div class="col-md-5">
            <% @ads.each do |ad| %>
                <%= link_to edit_ad_path(ad), class: "list-group-item" do %>
                    <div class="edit-icon pull-right"><i class="fa fa-pencil"></i></div>
                    <h4 class="list-group-item-heading"><%= number_to_currency ad.budget, unit: "R$", delimiter: ".", separator: "," =%></h4>
                    <p class="list-group-item-text small"><%= pluralize ad.creatives.count, "creative" =%>, <%= pluralize ad.targetings.count, "targeting" =%>.</p>
                <% end %>
            <% end %>
            
            <div class="text-center">
                <%= will_paginate @ads, renderer: BootstrapPagination::Rails, previous_label: "<", next_label: ">" %>
            </div>
        </div>
        <div class="col-md-7"></div>
    </div>
</div>

app/views/ads/new.html.erb
<% if @ad.new_record? %>
  <% provide(:title, "Create new Ad") %>
  <h2>New Ad</h2>
<% else %>
  <% provide(:title, "Edit Ad") %>
  <h2>Edit Ad</h2>
<% end %>
<div class="row">
  <div class="col-md-8">
    <%= nested_form_for @ad, validate: true do |f| %>
      <%= render 'shared/error_messages' %>
      <div class="form-group">
        <%= f.label :budget, class: "control-label" %>
        <%= f.text_field :budget, class: "form-control" %>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading text-right section-title">Creatives</div>
        <div class="panel-body">
          <div class="form-group">
              <%= f.fields_for :creatives, validate: true do |creative_form| %>
                <div class="panel panel-default">
                  <div class="panel-body">
                    <div class="row">
                      <div class="col-md-4">
                        <%= creative_form.label :bid, class: "control-label" %>
                        <%= creative_form.text_field :bid, class: "form-control" %>
                      </div>
                      <div class="col-md-6">
                        <%= creative_form.label :ad_text, class: "control-label" %>
                        <%= creative_form.text_area :ad_text, class: "form-control" %>
                      </div>
                      <div class="col-md-2 text-right">
                        <%= creative_form.link_to_remove "Remove" %>
                      </div>
                    </div>
                  </div>
                </div>
              <% end %>
              <p><%= f.link_to_add "Add a creative", :creatives %></p>
            </div>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading text-right section-title">Targetings</div>
        <div class="panel-body">
          <div class="form-group">
            <%= f.fields_for :targetings, validate: true do |targeting_form| %>
              <div class="panel panel-default">
                <div class="panel-body">
                  <div class="row">
                    <div class="col-md-6">
                      <%= targeting_form.label :places, class: "control-label" %>
                      <%= targeting_form.select :places, 
                        options_for_select([["Recife - PE", "recife"],
                                            ["São Paulo - SP", "são paulo"], 
                                            ["Rio de Janeiro - RJ", "rio de janeiro"], 
                                            ["Belo Horizonte - MG", "belo horizonte"]], 
                                            selected: targeting_form.object.places), {}, 
                                            { multiple: true, class: "form-control input" } %>
                    </div>
                    <div class="col-md-4">
                      <%= targeting_form.label :gender, class: "control-label" %>
                      
                      <div class="radio">
                        <label>
                          <%= targeting_form.radio_button :gender, :male %> Male
                        </label>
                      </div>
                      <div class="radio">
                        <label>
                          <%= targeting_form.radio_button :gender, :female %> Female
                        </label>
                      </div>
                      <div class="radio">
                        <label>
                          <%= targeting_form.radio_button :gender, :undetermined %> Undetermined
                        </label>
                      </div>  
                    </div>  
                    <div class="col-md-2 text-right">
                        <%= targeting_form.link_to_remove "Remove" %>
                    </div>    
                  </div>
                </div>    
              </div>
            <% end %>
          </div>
          <p><%= f.link_to_add "Add a targeting", :targetings %></p>
        </div>
      </div>
      <div class="form-group">
        <% if @ad.new_record? %>
          <%= f.submit "Create ad", class: "btn btn btn-primary" %>
        <% else %>  
          <%= f.submit "Update ad", class: "btn btn btn-primary" %>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="col-md-4"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | MiniAds</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', 'https://fonts.googleapis.com/css?family=Suravaram' %>
  <%= stylesheet_link_tag    'application', 'https://fonts.googleapis.com/css?family=Open+Sans' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <%= link_to "MiniAds", root_path, class: "navbar-brand" %>
      </div>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @ad.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@ad.errors.count, "error") %>.
    </div>
    <ul>
    <% @ad.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>